name: Continuous Integration
on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build -- --noEmit

      - name: Lint
        run: yarn lint